name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: download libraries
      run: |
        choco install --limit-output --no-progress wkhtmltopdf
        New-Item -ItemType Junction -Path "C:\wkhtmltopdf" -Target "C:\Program Files\wkhtmltopdf"
    - name: Build
      run: |
        Set-Item -Path Env:CGO_LDFLAGS -Value "-LC:\wkhtmltopdf\bin"
        Set-Item -Path Env:CGO_CFLAGS -Value "-IC:\wkhtmltopdf\include"
        go get
        go build
        dir .
        dir C:\wkhtmltopdf\bin
    - name: Bump version and push tag
      if: ${{ github.ref == 'refs/heads/main' }}
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: ncipollo/release-action@v1
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        artifacts: "wizo-schedule.exe"
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
